Federated/storage
aws-amplify/amplify-flutter pull request #1407
Opened 2022-02-25 19:00 UTC by fjnoyp

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-03-07 16:45 UTC, haverchuck commented on packages/storage/amplify_storage_s3/example/pubspec.yaml
> +    path: ../../../amplify_auth_cognito
This will need to be` auth/amplify_auth_cognito`

2022-03-07 16:48 UTC, haverchuck commented on packages/storage/amplify_storage_s3_android/.packages
> +# This file is deprecated. Tools should instead consume
I don't think this should be checked in.

2022-03-07 16:51 UTC, haverchuck requested changes
Please see comments inline.

2022-03-09 23:22 UTC, haverchuck approved these changes

2022-03-11 23:10 UTC, Jordan-Nelson approved these changes

2022-03-12 01:32 UTC, merged