Next
aws-amplify/amplify-flutter pull request #2425
Opened 2022-11-28 22:04 UTC by MarlonJD

*Same Issue #2277 and #1814 on the amplify_api 1.0.0-next.1,

*Description of changes:*
It's #2087 for next branch. Thanks for @fjnoyp

2022-11-29 15:21 UTC, ragingsquirrel3 commented
@MarlonJD thanks for opening this. Request: could you please cherry pick the commit from main rather than making new commits with same changes? You should just be able to run `git cherry-pick 7c14f79fb247ec8725f8fdf7a6a86ce5ea47494e` to get the changes from https://github.com/aws-amplify/amplify-flutter/commit/7c14f79fb247ec8725f8fdf7a6a86ce5ea47494e . That way, the same commit will be on both branches which helps to organize the git history.

2022-11-29 19:12 UTC, ragingsquirrel3 commented
@MarlonJD yes would either fix conflicts while doing cherry-pick (and callout in PR diff where the conflicts were), or alternatively add 1 extra commit after the cherry-picked commit whose commit message makes it clear that it is fixing code from previous commit. If you add an extra commit, would suggest to keep amending that commit for all the other changes in this PR so that this PR would have max 2 commits. Like I said, the end goal is that we have the original commit from main on next. thanks again!

2022-11-29 19:45 UTC, MarlonJD commented
Okay thanks for your detailed answer. So I'll  do cherry pick and merge commit then create pr again

2022-11-29 20:41 UTC, MarlonJD commented
@ragingsquirrel3 I did what you described, merged 2 confict. Can you check ?

2022-11-30 17:21 UTC, ragingsquirrel3 commented
Thanks, will review!

2022-11-30 18:15 UTC, ragingsquirrel3 requested changes
Thanks again for doing this! I just left a few suggestions regarding updates needed for next branch, might have been related to conflicts. You can create a new commit with title "chore(api): update conflicts from #2087" with these changes. There will also be some formatting changes needed as lint requirements are stricter on this branch. To check those, you can run `cd packages/api/amplify_api && flutter analyze`. I will also enable the CI checks for you.

2022-11-30 18:15 UTC, ragingsquirrel3 commented on packages/api/amplify_api/test/graphql_helpers_mtm_test.dart
> +}
```suggestion
class MockAmplifyAPI extends AmplifyAPIDart {
  MockAmplifyAPI({
    super.modelProvider,
  });
}
```

2022-11-30 18:15 UTC, ragingsquirrel3 commented on packages/api/amplify_api/test/graphql_helpers_mtm_test.dart
> +                  request: req, data: data, errors: errors);
```suggestion
      const data = {
        'listFirstMtmRelations': {
          'items': [
            {
              'id': 'id-first-mtm-relation',
              'manyToManyPrimary': {
                'id': 'id-mtm-primary',
                'name': 'mtm primary'
              },
              'manyToManySecondary': {
                'id': 'id-mtm-secondary',
                'name': 'mtm secondary'
              }
            }
          ]
        }
      };

      final response = GraphQLResponseDecoder.instance
          .decode<PaginatedResult<FirstMtmRelation>>(
        request: req,
        response: {
          'data': data,
          'errors': null,
        },
      );
```

2022-11-30 18:50 UTC, dnys1 approved these changes

2022-11-30 21:56 UTC, MarlonJD commented
I'm trying to fix conficts and prepairing changes.

2022-11-30 23:22 UTC, MarlonJD commented
Rebase changes for only for 2 commit

2022-12-01 14:55 UTC, ragingsquirrel3 commented
@MarlonJD good question. The contributing tips are a little different on next. You have to bootstrap the repo with `aft bs` instead of `melos bootstrap`:
* from root of repo, install `aft` w command `dart pub global activate -spath packages/aft`
* bootstrap by running `aft bs`

That will build the worker JS file locally.
More info https://github.com/aws-amplify/amplify-flutter/blob/next/CONTRIBUTING.md#amplify-flutter-repo-tool-aft

2022-12-02 14:35 UTC, ragingsquirrel3 commented
thanks @MarlonJD, tests passed locally for me. This is looking pretty good on my end. I'm just checking a few things then will approve/merge or let you know if other changes requested.

2022-12-02 14:58 UTC, ragingsquirrel3 approved these changes
thanks again @MarlonJD . Also thanks for bearing w me on cherry picking the commit and correcting for updated lint rules.

2022-12-02 14:59 UTC, merged

2022-12-02 15:27 UTC, MarlonJD commented
@ragingsquirrel3 thank you for your support and patience. Happy to see it merged.