chore(release): updated changelogs for 0.1
aws-amplify/amplify-flutter pull request #387
Opened 2021-02-13 01:31 UTC by fjnoyp

*Issue #, if available:*

*Description of changes:*
Update changelogs for 0.1

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-02-13 01:50 UTC, haverchuck commented on packages/amplify_auth_cognito/CHANGELOG.md
> +- fix: force signOut when signedIn (#369)
include
`- fix(amplify_auth_cognito): deprecates globalSignOut; simple user check upon Android signIn`

2021-02-13 02:32 UTC, jamesonwilliams approved these changes

2021-02-13 02:33 UTC, haverchuck commented on example/pubspec.yaml
> +  amplify_flutter: 0.1
are you sure two digit version is valid?

2021-02-13 02:48 UTC, Ashish-Nanda commented on example/pubspec.yaml
> +  amplify_storage_s3: 0.1
Can we make it `0.1.0` throughout the PR please?

2021-02-13 03:44 UTC, Amplifiyer commented
the version field  of the package in the pubspec.yaml also needs to be updated.

2021-02-13 03:52 UTC, Ashish-Nanda approved these changes
LGTM

2021-02-14 23:31 UTC, Ashish-Nanda requested changes
Please update the version field of the `pubspec.yaml` to `0.1.0` as well for the packages.

2021-02-15 00:58 UTC, Ashish-Nanda approved these changes
LGTM

2021-02-15 19:43 UTC, Amplifiyer approved these changes

2021-02-15 19:45 UTC, Ashish-Nanda approved these changes
Looks good

2021-02-15 19:46 UTC, merged