feat(amplify_api): GraphQL Helpers Integration Tests
aws-amplify/amplify-flutter pull request #785
Opened 2021-08-06 16:56 UTC by Equartey

*Issue #, if available:*
Partial implementation of GraphQL model helper feature #308. 

*Description of changes:*
This PR introduces integration tests to validate the GraphQL helpers against a real endpoint. Includes tests for: `get`, `list`, `create`, `update`, and `delete`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-06 17:27 UTC, ragingsquirrel3 commented on packages/amplify_api/lib/src/graphql/model_mutations_factory.dart
> +    Map<String, dynamic> variables = {"input": model.toJson()};
I have not looked at why unit tests are failing, but I would guess tests need to be updated to match this?

2021-08-06 19:16 UTC, dnys1 approved these changes
Looks good! Just fix up those failing tests and make the few changes I outlined and you'll be good to go 🚀

2021-08-06 19:54 UTC, ragingsquirrel3 requested changes

2021-08-06 19:54 UTC, ragingsquirrel3 commented on packages/amplify_api/example/integration_test/graph_ql_tests.dart
> +    });
suggestion: query the list of blogs before and after the delete to ensure the blog was actually deleted. Easiest way is to check the count of the result, ensure it went down by 1. Alternatively, you could query the list after the delete, iterate over all the blogs and ensure the blog not in the list result.

2021-08-09 17:18 UTC, Equartey commented on packages/amplify_api/example/integration_test/graph_ql_tests.dart
> +      if (blogIds.length == 0) {
Good catch, this is never touched and it's been omitted.

2021-08-09 17:19 UTC, Equartey commented on packages/amplify_api/example/integration_test/graph_ql_tests.dart
> +      blogIds.forEach((e) async {
Taking the delicate approach so we don't blow up someone's backend unexpectedly.

2021-08-09 17:20 UTC, Equartey commented on packages/amplify_api/example/integration_test/graph_ql_tests.dart
> +      expect(data.items.length, greaterThanOrEqualTo(3));
I've updated the assertion.

2021-08-09 20:39 UTC, ragingsquirrel3 commented on packages/amplify_api/lib/src/graphql/graphql_response_decoder.dart
> +              "Current GraphQLResponse is non-nullable, please insure item exists before fetching");
nit: insure -> ensure

2021-08-09 20:39 UTC, ragingsquirrel3 approved these changes
🚢  it w a typo. Nice job!

2021-08-09 20:45 UTC, Equartey commented on packages/amplify_api/lib/src/graphql/graphql_response_decoder.dart
> +      if (T == String || T == dynamic) {
Will be addressing in another PR.

2021-08-09 20:45 UTC, merged

2021-08-31 10:01 UTC, rahul-readwhere commented
Any comment on the release of this version to pub.dev ?

2021-08-31 21:42 UTC, ragingsquirrel3 commented
@rahul-readwhere the model helper branch needs to have some more updates and features before it is released to pub.dev. We are still working on subscriptions, getting/parsing nested models, query predicates and some helper methods related to paginated requests.

2021-09-01 05:16 UTC, rahul-readwhere commented
@ragingsquirrel3 any time frame decided ? or will it depend on the features that will be added. Thanks for sharing :)